# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1e33eacef970f259a8d20901d443c42f"
name = "snapshots-app-2"
handle = "snapshots-app-2"
application_url = "https://tab-disputes-rate-suffer.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-614f6c82.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://tab-disputes-rate-suffer.trycloudflare.com/auth/callback",
  "https://tab-disputes-rate-suffer.trycloudflare.com/auth/shopify/callback",
  "https://tab-disputes-rate-suffer.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
