# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e1bf507384b33ba72da1b5375d7b3bfa"
name = "snapshots 2"
handle = "snapshots-2"
application_url = "https://lawsuit-whats-knives-tulsa.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-614f6c82.myshopify.com"

[auth]
redirect_urls = [
  "https://lawsuit-whats-knives-tulsa.trycloudflare.com/auth/callback",
  "https://lawsuit-whats-knives-tulsa.trycloudflare.com/auth/shopify/callback",
  "https://lawsuit-whats-knives-tulsa.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
